[package]
name = "lwk_wollet"
version = "0.2.0"
edition = "2021"
autotests = false
description = "Liquid Wallet Kit - Watch-only wallet based on CT Descriptors"
license = "MIT OR BSD-2-Clause"
documentation = "https://docs.rs/lwk_wollet"

[lib]
crate-type = ["lib"]

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.2"
aes-gcm-siv = "0.10.0"
electrum-client = { version = "0.19.0", optional = true }
bip39 = "2.0.0"
elements-miniscript = { version = "0.3", features = ["serde"] }
thiserror = "1.0.48"
once_cell = "1.18.0"
elements = { version = "0.24.0", features = ["base64"] }
lwk_common = { version = "0.2.0" }
ehttp = { version = "*", optional = true }


#registry
idna = "0.4.0"
regex = "1.9.6"

tracing = "0.1"

[dev-dependencies]
tempfile = "3.8.0"
lwk_signer = { version = "0.2.0" }
lwk_jade = { version = "0.2.0" }
lwk_containers = { path = "../lwk_containers" }
minreq = { version = "2.9", features = ["https", "json-using-serde"] }
lwk_test_util = { path = "../lwk_test_util" }

[features]
default = ["electrum"]
serial = ["lwk_jade/serial"]
esplora = ["ehttp"]
electrum = ["electrum-client"]

[[test]]
name = "e2e"
path = "tests/e2e.rs"
