variables:
  CI_DISPOSABLE_ENVIRONMENT: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

.base:
  image: xenoky/lwk-builder@sha256:bed4b76fc94e0ec824c33fa153313212906f23069525ce15b199330ef548c9cc
  tags:
    - cloud
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - stuck_or_timeout_failure  
  services:
    - docker:20.10.12-dind


fmt_clippy:
  extends: .base
  script:
    - cargo fmt --check
    - cargo clippy --all-targets -- -D warnings

test_wollet:
  extends: .base
  script:
    - docker pull xenoky/local-jade-emulator:1.0.27
    - cp ./context/env.sh / && cd / && . ./env.sh && cd -
    - cargo test -p lwk_wollet -p lwk_signer

test_jade:
  extends: .base
  variables:
      TMPDIR: ${CI_PROJECT_DIR}  # otherwise issue with the docker
  script:
    - docker pull tulipan81/blind_pin_server:v0.0.5
    - docker pull xenoky/local-jade-emulator:1.0.27
    - cargo test -p lwk_jade

test_ledger:
  extends: .base
  script:
    - cargo test -p lwk_ledger

test_serial:
  extends: .base
  script:
    - cargo test --no-run --features serial

# run tests for minor crates all together
test_minor:
  extends: .base
  script:
    - cargo test -p lwk_tiny_jrpc -p lwk_app -p lwk_containers -p lwk_common -p lwk_hwi -p lwk_rpc_model -p lwk_signer

test_cli:
  extends: .base
  script:
    - cp ./context/env.sh / && cd / && . ./env.sh && cd -
    - cargo test -p lwk_cli

test_coverage:
  extends: .base
  variables:
    RUSTFLAGS: "-C instrument-coverage"
    LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
    TMPDIR: ${CI_PROJECT_DIR}  # otherwise issue with the docker

  script:
    - docker pull tulipan81/blind_pin_server:v0.0.5
    - docker pull xenoky/local-jade-emulator:1.0.27
    - cp ./context/env.sh / && cd / && . ./env.sh && cd -
    - cargo nextest run --features foreign_bindings --profile ci
    - grcov . -s . --binary-path ./target/debug/ -t cobertura --branch --ignore-not-existing --ignore "*cargo*" -o ./target/coverage.xml -p $(pwd)
    - "xmllint --xpath \"concat('Coverage: ', 100 * string(//coverage/@line-rate), ' perc')\" target/coverage.xml"
    - grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing --ignore "*cargo*" -o ./target/coverage/ -p $(pwd)
  coverage: '/Coverage: \d+(?:\.\d+)?/'
  artifacts:
    paths:
      - target/coverage.xml
      - target/coverage/
      - target/nextest/ci/junit.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/coverage.xml
      junit: target/nextest/ci/junit.xml

build_cli:
  extends: .base
  only:
    - master@liquid/lwk
  script:
    - cargo build --release -p lwk_cli
  artifacts:
    paths:
      - target/release/lwk_cli
    when: always
    expire_in: 14 days

audit:
  extends: .base
  script:
    # ignore unmantained serde_cbor
    - cargo audit -D warnings --ignore RUSTSEC-2021-0127

doc:
  extends: .base
  variables:
    RUSTDOCFLAGS: "-D warnings"
  script:
    - cargo doc --no-deps

examples:
  extends: .base
  script:
    - cargo run --example list_transactions

bindings:
  extends: .base
  script:
    - cp ./context/env.sh / && cd / && . ./env.sh && cd -
    - cargo test -p lwk_bindings --features foreign_bindings

check_rust_170:
  extends: .base
  script:
    - cargo update -p bumpalo --precise 3.14.0
    - cargo +1.70.0 check

wasm:
  extends: .base
  script:
    - cargo check --target wasm32-unknown-unknown -p lwk_common -p lwk_rpc_model -p lwk_containers -p lwk_hwi 
    - cargo check --target wasm32-unknown-unknown -p lwk_wollet --no-default-features --features esplora_wasm
    - cargo check --target wasm32-unknown-unknown -p lwk_signer --no-default-features
    - cargo check --target wasm32-unknown-unknown -p lwk_jade --no-default-features
    - cd lwk_wasm && WASM_BINDGEN_TEST_TIMEOUT=60 wasm-pack test --chrome --headless
