on:
  push:
    branches:
      - master
  pull_request: {}

name: Build framework for SwiftPM package

jobs:

  framework:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.75.0
        with:
          targets: x86_64-apple-ios,aarch64-apple-ios,aarch64-apple-ios-sim
      - uses: extractions/setup-just@v1
        with:
          just-version: 1.5.0  # optional semver specification, otherwise latest
      - run: just swift
      - uses: actions/upload-artifact@v4
        with:
          name: lwk.xcframework
          path: target/lwk.xcframework
      - uses: actions/upload-artifact@v4
        with:
          name: interface 
          path: target/swift
